name: publish-gpr-npm-package

on:
  workflow_call:
    inputs:
      node-version-file:
        description: Path to Node version file.
        required: true
        type: string
      prerelease:
        description: True if the release is a prerelease.
        required: true
        type: boolean
        default: false
      branch:
        description: Branch to push the version bump commit to.
        type: string
        default: main
      committer-name:
        description: Name of the committer for the version bump commit.
        required: true
        type: string
      committer-email:
        description: Email of the committer for the version bump commit.
        required: true
        type: string
    secrets:
      # This token MUST have the following permissions:
      #
      #   permissions:
      #    contents: write
      #    packages: write
      #    pull-requests: write
      gh_token:
        description: GitHub token with write:packages permissions.
        required: true

env:
  NODE_AUTH_TOKEN: ${{ secrets.gh_token }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout calling repo
        uses: actions/checkout@v4
        with:
          # see https://stackoverflow.com/a/63709189
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ inputs.node-version-file }}
          cache: yarn

      - name: Verify existence of release strategy
        run: yarn version check

      - name: Install package dependencies
        run: yarn install

      - name: Build package
        run: yarn build

      - name: Bump prerelease version
        if: ${{ inputs.prerelease }}
        run: yarn version apply --prerelease

      - name: Bump release version
        if: ${{ ! inputs.prerelease }}
        run: yarn version apply

      - name: Publish package to GitHub Packages Registry
        run: yarn npm publish

      - name: Commit version
        run: |
          git config --global user.name "${{ inputs.committer-name }}"
          git config --global user.email "${{ inputs.committer-email }}"
          version="$(jq -r .version < ./package.json)"
          branch="mcevoypeter/publish-gpr-npm-package/version-bump/$version"
          git checkout -b $branch
          git commit -am "Bump version to $version"
          git push -u origin $branch
          gh pr create --base ${{ inputs.branch }} --fill
          gh pr merge --merge
        env:
          GH_TOKEN: ${{ secrets.gh_token }}
